spring:
  redis:
    host: localhost
    port: 6379
    timeout: 3600ms
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
  kafka:
    #代理地址 可以多个
    bootstrap-servers: 127.0.0.1:9092
    ##################### provider  ######################
    producer:
      retries: 3
      # 批量发送消息的数量
      batch-size: 16384
      buffer-memory: 33554432
      # 指定指定key 和 消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    ##################### consumer  ######################
    # 指定默认消费者group id
    consumer:
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
# MQTT server param
mqtt:
  enabled: true
  host: 0.0.0.0
  port: 8282
  adaptor: JsonMqttAdaptor
  timeout: 10000
  netty:
    leak_detector_level: DISABLED
    boss_group_thread_count: 1
    worker_group_thread_count: 8
    max_payload_size: 65536